const obj = {
    Client: require("./client"),
    uptimer: require("./methods/uptimer"),
    capsPercantage: require("./methods/capsPercantage"),
    linkDetector: require("./methods/linkDetector"),
    takeAction: require("./methods/takeAction"),
    getMuteRole: require("./methods/getMuteRole"),
    numberToPunishment: require("./methods/numberToPunishment"),
    changeName: require("./methods/changeName"),
    delay: require("./methods/delay"),
    createWelcomeImage: require("./methods/createWelcomeImage"),
    createLeaveImage: require("./methods/createLeaveImage"),
    guildData: require("./types/guildData"),
    guildMemberData: require("./types/guildMember"),
    userData: require("./types/userData"),
    botData: require("./types/botData"),
    commandLogData: require("./types/commandLogs"),
    modules: require("./types/module"),
    powers: require("./types/powers"),
    punishment: require("./types/punishment"),
    page: require("./page"),
    wait: require("./wait"),
    getPower: require('./getPower'),
    getMutedRole: require('./getMutedRole'),
    getOptions: require("./getOptions"),
    commandLogs: require("./commandLogs"),
    guildData: require("./guildData"),
    guildMember: require("./guildMember"),
    userData: require("./userData"),
}

module.exports = obj;